version: "3.9"

services:
  web:
    build: .
    container_name: greenmart-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/instance
    environment:
      FLASK_ENV: development

volumes:
  sqlite_data:
